services:
  db:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: maria
      MARIADB_DATABASE: springbootdb
      MARIADB_USER: root
      MARIADB_PASSWORD: maria
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  application:
    container_name: imarium-backend
    image: seeyou2000/imarium_backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ./gradlew build
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/springbootdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "maria"
    depends_on:
      db:
        condition: service_healthy

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
