name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: maria
          MARIADB_DATABASE: springbootdb
          MARIADB_USER: root
          MARIADB_PASSWORD: maria

    env:
      DB_HOST: mariadb           # 서비스 이름으로 변경
      DB_PORT: 3306
      DB_DATABASE: springbootdb
      DB_USERNAME: root
      DB_PASSWORD: maria

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          port: 22
          script: |
            cd /home/ubuntu
            if [ ! -d ".git" ]; then
                git clone https://github.com/Seeyou2000/imarium-backend.git .
            else
                git pull origin main
            fi
            cd /home/ubuntu/imarium-backend
            docker-compose down
            docker-compose up -d --build
          
